### ISSUE TITLE
Beschreibung der geplanten Applikation

### ISSUE THREAD

**Issue by ahocevar** [tuwien-geoweb/g10-2014#17]
Ganz wichtig für die Projektplanung ist, dass ihr die geplante Applikation beschreibt:
- Anforderungen aus Benutzersicht, d.h. was soll die App können. Kann z.B. in Form von Anwendungsfällen (use cases) beschrieben werden.
- User Interface Design, z.B. mit einer handgezeichneten Skizze oder einem Screenshot.
- Liste der Daten, die benötigt werden.

**Comment by Witoldurbanski** [comment]
Wir haben jetzt eine kurze Beschreibung hinzugefügt.
https://github.com/tuwien-geoweb/g10-2014/blob/gh-pages/uebung/Allgemeine%20Beschreibung_Wohnstandortanalyse.docx
@ahocevar 

Um ein Feedback wird gebeten.

**Comment by ahocevar** [comment]
Das passt so - ihr könnt loslegen!
