### ISSUE TITLE
Problem mit der Datenbank

### ISSUE THREAD

**Issue by Witoldurbanski** [tuwien-geoweb/g10-2014#18]
Wir haben versucht die Datenbanktabellen miteinander zu verknüpfen und die Standardabweichung zu berechnen, so wie es in der Übung gemacht wurde, nur irgendwie bekommen wir einen Fehler an der Stelle wo die Auswahl reingeladen werden sollte (%column%) . Hier ein Screenshot:
https://github.com/tuwien-geoweb/g10-2014/blob/gh-pages/DB-Sql.png

@ahocevar

**Comment by ahocevar** [comment]
`%column%` ist ein Platzhalter, der von GeoServer mit dem Wert aus dem WMS-Request (`&viewparams=column:spaltenname`) befüllt wird. spatialite-gui weiß davon natürlich nichts. Zwei Möglichkeiten zum Testen: 1) ihr nehmt die gleiche Abfrage in GeoServer für die Layer-Definition aus einer SQL-View, oder 2) ihr ersetzt in spatialite-gui den Text `%column` durch einen gültigen Spaltennamen.
