### ISSUE TITLE
Funktionsproblem Browser

### ISSUE THREAD

**Issue by Witoldurbanski** [tuwien-geoweb/g10-2014#21]
wir haben ein Problem mit der Anzeige der Karten. Es ist nämlich Browserabhängig was angezeigt wird. Im Safari und Google Chrome wird alles richtig dargestellt, jedoch im Firefox und Internet Explorer gibt es Probleme mit DataDict und somit mit der Anzeige der demographischen Layer.

Ist das ein bekanntes Problem oder haben wir etwas falsch gemacht?

@ahocevar

**Comment by ahocevar** [comment]
Auf die Schnelle kommt mir das, was ihr schildert, nicht bekannt vor. Kann man das irgendwo live ausprobieren? Welches Problem mit DataDict meint ihr genau?

**Comment by SebastianVcelar** [comment]
Hier der Link zum ausprobieren:
http://tuwien-geoweb.github.io/g10-2014/uebung/wohnstandortanalyse.html
@ahocevar

**Comment by ahocevar** [comment]
Versucht einmal, den DOCTYPE eures `wohnstandortanalyse.html` Dokuments zu ändern von

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
```

auf

``` html
<!DOCTYPE html>
```

Das Problem kommt durch inkompatible Zeichensätze, und der HTML5 doctype sollte dieses Problem beheben.

**Comment by ahocevar** [comment]
Siehe #22.
