### ISSUE TITLE
Geoserver ist Down

### ISSUE THREAD

**Issue by Witoldurbanski** [tuwien-geoweb/g10-2014#23]
@ahocevar @jbroetha

**Comment by jbroetha** [comment]
Geoserver wurde wieder gestartet …

MfG
Johann Bröthaler

Von: Witoldurbanski [mailto:notifications@github.com]
Gesendet: Donnerstag, 08. Jänner 2015 12:01
An: tuwien-geoweb/g10-2014
Cc: Bröthaler Johann
Betreff: [g10-2014] Geoserver ist Down (#23)

@ahocevarhttps://github.com/ahocevar @jbroethahttps://github.com/jbroetha
