### ISSUE TITLE
Geoserver Probleme (sqlite error)

### ISSUE THREAD

**Issue by SebastianVcelar** [tuwien-geoweb/g10-2014#24]
Wir haben ein Problem mit dem Geoserver:
1. Wir können keine Layer mehr aus einer Datenbank publizieren. 
2. Die vorhanden Layer werden weder in HTML noch in der Geoserver Layer Preview angezeigt.
   Nach Klick in die Map im Popup erhalten wir folgende Fehlermeldung: 

"Mit dieser XML-Datei sind anscheinend keine Style-Informationen verknüpft. Nachfolgend wird die Baum-Ansicht des Dokuments angezeigt.
      <ServiceExceptionReport version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://student.ifip.tuwien.ac.at/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd"><ServiceException>
      java.lang.RuntimeException: Error getting FeatureType, this should never happen!
Error getting FeatureType, this should never happen!
Error occurred building feature type
[SQLITE_ERROR] SQL error or missing database (no such table: daten_vie)
</ServiceException></ServiceExceptionReport>"

Fehler kommt dann auch in der Layer Preview.
1. Wir können aber ein Shapefile als Datenspeicher auswählen und dieses publizieren.
   Dann sieht man die Layer Preview aber in der Map keine Punkte. 

@ahocevar 
Mit der Bitte um Hilfe.

**Comment by Witoldurbanski** [comment]
könnte es an den Schreibrechten der Datenbank liegen?

**Comment by ahocevar** [comment]
Bitte um eine genauere Beschreibung des Problems:
- Welcher store bzw. Datenspeicher?
- Welcher Layer?
- Wo kann ich das Problem live sehen?

**Comment by SebastianVcelar** [comment]
Arbeitsbereich = g10_2014
Datenspeicher = geodata_gr10
Layer = alle (heißt keiner funktioniert)

Anschauen am besten direkt am Geoserver in der Layer Vorschau einen der Punktlayer (z.B. Schulen) anschauen. Diese werden nicht angezeigt.

Wir bekommen wenn wir einen neuen Layer publizieren wollen eine Fehlermeldung sobald wir die Bounding Box automatisch berechnen lassen wollen.

**Comment by ahocevar** [comment]
Wie schon öfters gesagt, darf in der Datenspeicher-Konfiguration kein Schema und kein Passwort angegeben sein. Ich hab jetzt beides gelöscht, es sollte nun also funktionieren.

**Comment by SebastianVcelar** [comment]
Vielen Dank, das hat uns echt Nerven gekostet. Ganz wissen wir auch nicht wie das passiert ist, besonders weil wir am bestehenden Datenspeicher seit er heute morgen funktioniert hat nichts geändert haben (außer dem Pfad zur SQLITE Datenbank). Naja, jetzt haben wirs uns aber sicher gemerkt! Nochmals Danke für die Hilfe.
