### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by SaschaM087** [tuwien-geoweb/g10-2014#6]
Abgabe Fertigstellung der ersten Online Karte

**Comment by SaschaM087** [comment]
Abgabe @ahocevar

**Comment by ahocevar** [comment]
Was ist der Link zur fertigen Karte? http://tuwien-geoweb.github.io/g10-2014/???

**Comment by SaschaM087** [comment]
Link zur fertigen Karte: http://tuwien-geoweb.github.io/g10-2014/Abgaben/einbindung_erste_map.html
